version: '2'
services:
    service1-app:
        image: service1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://service1-postgresql:5432/service1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    service1-postgresql:
        extends:
            file: postgresql.yml
            service: service1-postgresql
